
* Curso de Visualización de Datos Urbanos Etopia 2021

Un repositorio con los contenidos del curso

1. Introducción y organización del curso
2. Herramientas
3. Limpieza de datos 
4. Análisis de datos
5. Visualización de datos
6. Puesta en común de los proyectos y cierre del curso

* Sesiones
** Sesión 1. 22/10
1. Presentación del curso, quiénes somos, etc.
2. Presentación de las personas participantes
3. Qué pretendemos con el taller
4. Un par de ejemplos: Ciudad Desigual y Territorio de Datos
   1. Ciudad Desigual: https://jllopc.github.io/ciudad.desigual/
   2. Territorio de datos: https://territoriodedatos.org
5. Debate entre historiadores y sociólogos, Ignacio Azcona
6. La línea de comandos
  - Cygwin y apt-cyg
  - Brew
  - WSL

** Sesión 2. 23/10
1. Charla de experiencias artísticas con la ciudad, Julián Pérez (ver [[file://src/pdf/slides-Julian.pdf][PDF]])
2. Configuración de la línea de comandos
3. Creación de grupo de Telegram
4. Creación de organización de Github
5. Herramientas de línea de comandos
** Sesión 3. 29/10 Viernes
*** Repaso
*** Mario Pérez-Montoro
Presentación en [[file://src/pdf/mpm-sesion-i.pdf][PDF]]
*** Github
**** Datos
- Organización: https://github.com/org/mpvdes
- Equipo: https://github.com/org/mpvdes/etopia
- Repositorio: https://github.com/mpvdes/etopia-2021
**** Ayuda
- Mi manual, https://github.com/flowsta/github
- Mi web, http://flowsta.github.io/github/
- Web oficial, https://git-scm.com/

**** Clonado y actualización del repositorio

** Sesión 4. 30/10, Sábado
*** Mario Pérez-Montoro
| Atributo | Cuali | Cuanti |
|----------+-------+--------|
|          |       |        |

- enchroma
- Tinta-dato y tinta-no-dato
*** DONE Repasar Github
*** DONE Repositorio Github propio
*** Configuración nano
*** Vídeo: aparcamientos en EE.UU.
*** Vídeo: casas en EE.UU
** Ejemplos
- NPR, Housing Segregation,  Let's Talk: Video housing segregation in everything, https://www.npr.org/sections/codeswitch/2018/04/11/601494521/video-housing-segregation-in-everything
- Serie: https://www.npr.org/series/718730324/video
*** R
R es un lenguaje de programación libre de análisis estadístico. Es decir, es similar a trabajar con:
- Excel, si lo utilizas con esa finalidad.
- SPSS, de IBM.
- Stata
- otros...
**** Trabajar con R
Hay varias opciones para trabajar con R:
- La propia consola de R que lanzamos desde la terminal.
- El programa GUI que abre la consola de R.
- El programa RStudio.

**** Instalación de la consola
De momento vamos a instalar la consola para las próximas sesiones:
- En Cygwin, =apt-cyg install R=
- En OSX, =brew install r= si no quieres la versión gráfica o =brew cask install r= si quieres la GUI de R.
- En Debian/Ubuntu GNU/Linux, =sudo apt install r-base=
**** Enlaces
- [[https://timogrossenbacher.ch/2015/12/why-data-journalists-should-start-using-r-in-2016/][Why data journalists should start using R in 2016]].
- [[https://smach.github.io/R4JournalismBook/HowDoI.html][How Do I?...(do that in R)]]
- http://rstudio-pubs-static.s3.amazonaws.com/6975_c4943349b6174f448104a5513fed59a9.html
- https://www.r-bloggers.com/cross-tabulation-with-xtabs-exercises/
**** BBPlot
   :PROPERTIES:
   :url:      https://github.com/bbc/bbplot
   :END:

R package that helps create and export ggplot2 charts in the style used by the BBC News data team
**** Katie Jolly
Es el caso de [[https://www.katiejolly.io/][Katie Jolly]] tal como explica en su artículo [[https://www.katiejolly.io/blog/2019-04-25/data-driven-design][Data Driven Design]]: Data-driven design in 'Curious City: In, Out, Above, Beyond Saint Paul', donde expone su interés por el llamado "information design" o diseño de información y cómo utiliza R y software de diseño gráfico para crear una visualización llamada "Turning the Page" para el libro "Curious City: In, Out, Above, Beyond Saint Paul".

#+caption: Trabajo final K. Jolly
https://www.katiejolly.io/blog//assets/curious-city/kjolly_final.png

El interés le vino siguiendo el trabajo de [[https://spatial.ly/][James Chesire]] que suponía que, dado que era un usuario de [[https://cran.r-project.org/][R]] y de [[https://ggplot2.tidyverse.org/][ggplot2]], igual usaba software libre.

https://www.katiejolly.io/blog//assets/curious-city/treasures_before_after.jpg

De hecho el ejemplo anterior está sacado del artículo [[http://theinformationcapital.com/coder-designer/][The coder and the designer]] donde cuenta su experiencia con R y cómo se apoya en sus visualizaciones para el arte final.
**** BBC R and Data Journalism Cookbook for R Graphics
   :PROPERTIES:
   :url:      https://bbc.github.io/rcookbook/
   :END:
At the BBC data team, we have developed an R package and an R cookbook to make the process of creating publication-ready graphics in our in-house style using R’s ggplot2 library a more reproducible process, as well as making it easier for people new to R to create graphics.

** Sesión 5. 5/11
*** Google Spreadsheet
**** ImportURL

#+begin_example
IMPORTHTML(url; consulta; índice)
#+end_example

#+begin_example
=IMPORTHTML("https://es.wikipedia.org/wiki/Esc%C3%A1ndalo_de_emisiones_contaminantes_de_veh%C3%ADculos_Volkswagen";"table";3)
#+end_example

#+begin_example
=IMPORTHTML("https://es.wikipedia.org/wiki/Esc%C3%A1ndalo_de_emisiones_contaminantes_de_veh%C3%ADculos_Volkswagen";"list";5)
#+end_example

#+begin_example
=IMPORTHTML("https://es.wikipedia.org/wiki/Esc%C3%A1ndalo_de_emisiones_contaminantes_de_veh%C3%ADculos_Volkswagen";"list";6)
#+end_example

#+begin_example
=IMPORTHTML("http://en.wikipedia.org/wiki/2012_Summer_Olympics_medal_table";"table";2)
#+end_example

#+begin_example
=IMPORTHTML("http://cincodias.com"; "table"; 2)
#+end_example
**** ImportXML
#+begin_example
=IMPORTXML("http://cincodias.com/cincodias/economia.html";"//div[@class='mod_i']//h3")
#+end_example
Otras opciones:
- =count(//div[@class='textoNovedadesSeccionInterior']//a/@href)=
- =//img/@alt=
- =//a[contains('Escuela')]/@href=

**** ImportFeed
#+begin_example
=importfeed("http://cincodias.com/rss/tags/ultimas_noticias.xml";"items url";VERDADERO;250)
#+end_example

url: http://www.ft.com/rss/home/europe
#+begin_example
=importfeed(B2;"items url";VERDADERO;250)
#+end_example

https://elpais.com/tag/dia_internacional_eliminacion_violencia_contra_la_mujer/a/
https://elpais.com/tag/rss/dia_internacional_eliminacion_violencia_contra_la_mujer/a
#+begin_example
=importfeed(C1;"items url";VERDADERO;250)
#+end_example

http://www.ejercito.mde.es/unidades/Madrid/index.html
http://www.ine.es/prensa/epa_tabla.htm

#+begin_example
=IMPORTHTML(C1;"table";2)
#+end_example
*** Open Refine
  - https://openrefine.org/
- "A free, open source, powerful tool for working with messy data"
- La navaja suiza de la limpieza de datos.
- En la versión 3.4.1, en la versión para Windows, está la opción de descargarlo con [[https://adoptopenjdk.net/about.html][OpenJDK]] incluido.

*** Python
**** csvkit
   :PROPERTIES:
   :url:      https://csvkit.readthedocs.io/en/latest/tutorial.html
   :END:
Instalación:
#+begin_example
pip install csvkit
#+end_example

**** Scikit learn
https://scikit-learn.org/stable/
**** Jupyter
Instalamos:
#+begin_example
pip install jupyter
#+end_example

Lanzamos:
#+begin_example
jupyter notebook
#+end_example

* Datos
- https://freesound.org/search/?q=zaragoza
- https://commons.wikimedia.org/w/index.php?search=zaragoza&title=Special:MediaSearch&go=Go&type=image
- https://archive.org/search.php?query=zaragoza
- https://www.gutenberg.org/ebooks/search/?query=zaragoza&submit_search=Go%21
- https://www.zaragoza.es/sede/portal/datos-abiertos/
- [[https://visdatasets.github.io/][Dataset for visualisation construction]]
- [[https://docs.google.com/spreadsheets/d/1oHcxlAbkTJmqfOxYQM22cvjjjRf5pETIF30x7L-qybc/edit#gid=0][The Guardian Polls]]
- [[http://aduanas.camaras.org/][Base de datos de comercio exterior]]
- [[http://www.cnmv.es/portal/home.aspx][CNMV]]
- http://www.ejercito.mde.es/unidades/Madrid/index.html
- http://www.ine.es/prensa/epa_tabla.htm
- https://visdatasets.github.io/
